//
//  AIGenerationState.swift
//  QuizFlash
//

import Foundation

// MARK: - AI Generation State

/// Represents the current phase of an AI flashcard generation pipeline.
///
/// Observe this value inside your ViewModel/View to drive progress UI.
public enum AIGenerationState: Equatable {
    /// No operation in progress.
    case idle
    /// The document is being analysed for its type and quality.
    case analyzingDocument
    /// Text is being extracted from the document.
    case extractingText
    /// Flashcards are being generated by the AI model.
    ///
    /// - Parameters:
    ///   - progress: A value in `[0.0, 1.0]` indicating pipeline completion.
    ///   - foundCount: The number of flashcards produced so far.
    case generatingCards(progress: Double, foundCount: Int)
    /// Generation failed with the associated error message.
    case error(String)

    public static func == (lhs: AIGenerationState, rhs: AIGenerationState) -> Bool {
        switch (lhs, rhs) {
        case (.idle, .idle),
             (.analyzingDocument, .analyzingDocument),
             (.extractingText, .extractingText):
            return true
        case (.generatingCards(let lp, let lc), .generatingCards(let rp, let rc)):
            return lp == rp && lc == rc
        case (.error(let l), .error(let r)):
            return l == r
        default:
            return false
        }
    }
}

// MARK: - PDF Quality Info

/// Diagnostic metadata returned after analysing a PDF document's text quality.
struct PDFAnalysisInfo {
    /// Normalised quality score in `[0.0, 1.0]`.
    let quality: Double
    /// Total number of pages in the document.
    let pageCount: Int
    /// Total number of characters extracted from the text layer.
    let extractedChars: Int

    /// The recommended extraction strategy based on quality.
    var recommendation: ExtractionMode {
        quality >= 0.8 ? .fast : .quality
    }

    /// A human-readable label describing the extraction quality.
    var qualityLabel: String {
        switch quality {
        case 0.8...: return "Text extracted successfully"
        case 0.5...: return "Text partially detected"
        default:     return "This PDF cannot be used – try another one"
        }
    }

    /// The SF Symbol name appropriate for the quality level.
    var qualityIcon: String {
        switch quality {
        case 0.5...: return "checkmark.circle.fill"
        default:     return "exclamationmark.triangle.fill"
        }
    }

    /// `true` when PDFKit direct extraction is reliable enough to skip OCR.
    var isGoodForFast: Bool { quality >= 0.8 }
}

/// The extraction strategy to use for a given document.
enum ExtractionMode: String {
    /// Direct PDFKit text extraction – fast and free.
    case fast = "fast"
    /// On-device Vision OCR or GPT Vision – higher quality, higher cost.
    case quality = "quality(Premium)"
}

// MARK: - AI Generation Options

/// Card-shape profile requested by the user for AI generation.
public enum AICardGenerationType: String, CaseIterable, Identifiable, Codable {
    case flashcards
    case match
    case quiz
    case write

    public var id: String { rawValue }

    var title: String {
        switch self {
        case .flashcards: return "Flash Cards"
        case .match: return "Match Cards"
        case .quiz: return "Quiz Cards"
        case .write: return "Write Cards"
        }
    }

    var subtitle: String {
        switch self {
        case .flashcards: return "Balanced active-recall question and answer cards."
        case .match: return "Short, pairable prompts and crisp matching answers."
        case .quiz: return "Multiple-choice prompts with one correct answer."
        case .write: return "Typed-answer prompts with exact recall focus."
        }
    }

    var systemImage: String {
        switch self {
        case .flashcards: return "rectangle.stack.fill"
        case .match: return "square.grid.2x2.fill"
        case .quiz: return "questionmark.square.dashed"
        case .write: return "pencil.and.scribble"
        }
    }
}

/// Depth and density profile requested by the user for generated cards.
public enum AICardGenerationLevel: String, CaseIterable, Identifiable, Codable {
    case simple
    case balanced
    case advanced

    public var id: String { rawValue }

    var title: String {
        switch self {
        case .simple: return "Simple"
        case .balanced: return "Balanced"
        case .advanced: return "Advanced"
        }
    }

    var subtitle: String {
        switch self {
        case .simple: return "Focus on the clearest core facts and definitions."
        case .balanced: return "Keep the current prompt style with normal depth."
        case .advanced: return "Prefer nuanced, technical, higher-order understanding."
        }
    }
}

/// Distribution mode used to decide how much of each source segment is sent to AI.
public enum AISourceDistributionMode: String, CaseIterable, Identifiable, Codable {
    case auto
    case manual

    public var id: String { rawValue }

    var title: String {
        switch self {
        case .auto: return "Auto"
        case .manual: return "Manual"
        }
    }

    var subtitle: String {
        switch self {
        case .auto: return "Distribute cards automatically based on detected text density."
        case .manual: return "Choose exact image or page ranges and assign card counts yourself."
        }
    }
}

/// One source range assigned to a target number of cards.
public struct AISourceRangeAllocation: Identifiable, Equatable, Codable {
    public var id: UUID
    public var startIndex: Int
    public var endIndex: Int
    public var cardCount: Int

    public init(
        id: UUID = UUID(),
        startIndex: Int,
        endIndex: Int,
        cardCount: Int
    ) {
        self.id = id
        self.startIndex = startIndex
        self.endIndex = endIndex
        self.cardCount = cardCount
    }
}

/// One logical text segment that can be routed independently through the AI
/// chunk planner (for example one OCR image or one PDF page).
public struct AITextSourceSegment: Identifiable, Equatable, Codable {
    public let id: UUID
    public let index: Int
    public let label: String
    public let text: String

    public init(
        id: UUID = UUID(),
        index: Int,
        label: String,
        text: String
    ) {
        self.id = id
        self.index = index
        self.label = label
        self.text = text
    }

    public var characterCount: Int {
        text.trimmingCharacters(in: .whitespacesAndNewlines).count
    }
}

/// User-controlled AI generation settings that shape both prompt behavior and
/// how the source document is chunked into real-time batches.
public struct AIGenerationOptions: Equatable, Codable {
    public var cardType: AICardGenerationType = .flashcards
    public var cardLevel: AICardGenerationLevel = .balanced
    /// Legacy persisted field kept for backward compatibility. Delivery is
    /// adaptive now and no longer uses a user-visible fixed batch size.
    public var cardsPerBatch: Int = 3
    public var sourceDistributionMode: AISourceDistributionMode = .auto

    public init(
        cardType: AICardGenerationType = .flashcards,
        cardLevel: AICardGenerationLevel = .balanced,
        cardsPerBatch: Int = 3,
        sourceDistributionMode: AISourceDistributionMode = .auto
    ) {
        self.cardType = cardType
        self.cardLevel = cardLevel
        self.cardsPerBatch = cardsPerBatch
        self.sourceDistributionMode = sourceDistributionMode
    }

    /// Resolves the per-request card quota adaptively for speed while keeping
    /// requests small enough for stable output quality.
    func resolvedCardsPerBatch(for targetCards: Int) -> Int {
        let safeTarget = max(targetCards, 1)

        let adaptiveBatchSize: Int
        switch safeTarget {
        case 1...4:
            adaptiveBatchSize = safeTarget
        case 5...12:
            adaptiveBatchSize = 4
        case 13...24:
            adaptiveBatchSize = 6
        case 25...50:
            adaptiveBatchSize = 8
        case 51...90:
            adaptiveBatchSize = 10
        default:
            adaptiveBatchSize = 12
        }

        return min(adaptiveBatchSize, safeTarget)
    }
}

// MARK: - AI Flashcard Model

/// A single flashcard generated by the AI pipeline.
public struct AIFlashcard: Identifiable, Codable, Sendable {
    public let id: UUID
    /// The question side content, zone-delimited with `AIZoneParser.zoneDelimiter`.
    public let question: String
    /// The answer side content, zone-delimited with `AIZoneParser.zoneDelimiter`.
    public let answer: String

    public init(id: UUID = UUID(), question: String, answer: String) {
        self.id = id
        self.question = question
        self.answer = answer
    }
}

// MARK: - AI Generation Response

/// The top-level wrapper decoded from the AI service JSON response.
public struct AIGenerationResponse: Codable {
    public let flashcards: [AIFlashcard]
}
