//
//  AIGenerationState.swift
//  QuizFlash
//

import Foundation
import SwiftUI

// MARK: - AI Generation State

/// Represents the current phase of an AI flashcard generation pipeline.
///
/// Observe this value inside your ViewModel/View to drive progress UI.
public enum AIGenerationState: Equatable, Sendable {
    /// No operation in progress.
    case idle
    /// The document is being analysed for its type and quality.
    case analyzingDocument
    /// Text is being extracted from the document.
    case extractingText
    /// Flashcards are being generated by the AI model.
    ///
    /// - Parameters:
    ///   - progress: A value in `[0.0, 1.0]` indicating pipeline completion.
    ///   - foundCount: The number of flashcards produced so far.
    case generatingCards(progress: Double, foundCount: Int)
    /// Generation failed with the associated error message.
    case error(String)

    public static func == (lhs: AIGenerationState, rhs: AIGenerationState) -> Bool {
        switch (lhs, rhs) {
        case (.idle, .idle),
             (.analyzingDocument, .analyzingDocument),
             (.extractingText, .extractingText):
            return true
        case (.generatingCards(let lp, let lc), .generatingCards(let rp, let rc)):
            return lp == rp && lc == rc
        case (.error(let l), .error(let r)):
            return l == r
        default:
            return false
        }
    }
}

// MARK: - PDF Quality Info

/// Diagnostic metadata returned after analysing a PDF document's text quality.
nonisolated struct PDFAnalysisInfo: Equatable, Sendable {
    /// Normalised quality score in `[0.0, 1.0]`.
    let quality: Double
    /// Total number of pages in the document.
    let pageCount: Int
    /// Total number of characters extracted from the text layer.
    let extractedChars: Int

    /// A human-readable label describing the extraction quality.
    var qualityLabel: String {
        switch quality {
        case 0.8...: return "Text extracted successfully"
        case 0.5...: return "Text partially detected"
        default:     return "This PDF cannot be used – try another one"
        }
    }

    func localizedQualityLabel(locale: Locale) -> String {
        switch quality {
        case 0.8...:
            return AppLocalization.string("Text extracted successfully", locale: locale)
        case 0.5...:
            return AppLocalization.string("Text partially detected", locale: locale)
        default:
            return AppLocalization.string("This PDF cannot be used – try another one", locale: locale)
        }
    }

    /// The SF Symbol name appropriate for the quality level.
    var qualityIcon: String {
        switch quality {
        case 0.5...: return "checkmark.circle.fill"
        default:     return "exclamationmark.triangle.fill"
        }
    }

    /// `true` when PDFKit direct extraction is reliable enough to skip OCR.
    var isGoodForFast: Bool { quality >= 0.8 }
}

// MARK: - AI Generation Options

/// Card-shape profile requested by the user for AI generation.
public enum AICardGenerationType: String, CaseIterable, Identifiable, Codable, Sendable {
    case flashcards
    case quiz

    public var id: String { rawValue }

    nonisolated var title: String {
        switch self {
        case .flashcards: return "Flash Cards"
        case .quiz: return "Quiz Cards"
        }
    }

    nonisolated func localizedTitle(locale: Locale) -> String {
        switch self {
        case .flashcards: return AppLocalization.string("Flash Cards", locale: locale)
        case .quiz: return AppLocalization.string("Quiz Cards", locale: locale)
        }
    }

    nonisolated var subtitle: String {
        switch self {
        case .flashcards: return "Active-recall question and answer cards."
        case .quiz: return "Multiple-choice prompts with one or more correct answers."
        }
    }

    nonisolated func localizedSubtitle(locale: Locale) -> String {
        switch self {
        case .flashcards:
            return AppLocalization.string("Active-recall question and answer cards.", locale: locale)
        case .quiz:
            return AppLocalization.string("Multiple-choice prompts with one or more correct answers.", locale: locale)
        }
    }

    nonisolated var systemImage: String {
        switch self {
        case .flashcards: return "rectangle.stack.fill"
        case .quiz: return "questionmark.square.dashed"
        }
    }

    /// The concrete AI response contract selected by this generation mode.
    nonisolated var outputContract: AIGeneratedCardContract {
        switch self {
        case .flashcards:
            return .flashcard
        case .quiz:
            return .quiz
        }
    }
}

/// Depth and density profile requested by the user for generated cards.
public enum AICardGenerationLevel: String, CaseIterable, Identifiable, Codable, Sendable {
    case simple
    case pro

    public var id: String { rawValue }

    var title: String {
        switch self {
        case .simple: return "Simple"
        case .pro: return "Pro"
        }
    }

    func localizedTitle(locale: Locale) -> String {
        switch self {
        case .simple: return AppLocalization.string("Simple", locale: locale)
        case .pro: return AppLocalization.string("Pro", locale: locale)
        }
    }

    var subtitle: String {
        switch self {
        case .simple: return "Short, useful cards focused on the essential idea."
        case .pro: return "Deeper cards with structure, context, and key nuance."
        }
    }

    func localizedSubtitle(locale: Locale) -> String {
        switch self {
        case .simple:
            return AppLocalization.string("Short, useful cards focused on the essential idea.", locale: locale)
        case .pro:
            return AppLocalization.string("Deeper cards with structure, context, and key nuance.", locale: locale)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValue = try container.decode(String.self)
        switch rawValue {
        case Self.simple.rawValue:
            self = .simple
        case Self.pro.rawValue, "balanced", "advanced":
            self = .pro
        default:
            self = .pro
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Distribution mode used to decide how much of each source segment is sent to AI.
public enum AISourceDistributionMode: String, CaseIterable, Identifiable, Codable, Sendable {
    case auto
    case manual

    public var id: String { rawValue }

    var title: String {
        switch self {
        case .auto: return "Auto"
        case .manual: return "Manual"
        }
    }

    func localizedTitle(locale: Locale) -> String {
        switch self {
        case .auto: return AppLocalization.string("Auto", locale: locale)
        case .manual: return AppLocalization.string("Manual", locale: locale)
        }
    }

    var subtitle: String {
        switch self {
        case .auto: return "Distribute cards automatically based on detected text density."
        case .manual: return "Choose exact image or page ranges and assign card counts yourself."
        }
    }

    func localizedSubtitle(locale: Locale) -> String {
        switch self {
        case .auto:
            return AppLocalization.string("Distribute cards automatically based on detected text density.", locale: locale)
        case .manual:
            return AppLocalization.string("Choose exact image or page ranges and assign card counts yourself.", locale: locale)
        }
    }
}

/// One source range assigned to a target number of cards.
public nonisolated struct AISourceRangeAllocation: Identifiable, Equatable, Codable, Sendable {
    public var id: UUID
    public var startIndex: Int
    public var endIndex: Int
    public var cardCount: Int

    public init(
        id: UUID = UUID(),
        startIndex: Int,
        endIndex: Int,
        cardCount: Int
    ) {
        self.id = id
        self.startIndex = startIndex
        self.endIndex = endIndex
        self.cardCount = cardCount
    }
}

/// One logical text segment that can be routed independently through the AI
/// chunk planner (for example one OCR image or one PDF page).
public struct AITextSourceSegment: Identifiable, Equatable, Codable, Sendable {
    public let id: UUID
    public let index: Int
    public let label: String
    public let text: String

    public init(
        id: UUID = UUID(),
        index: Int,
        label: String,
        text: String
    ) {
        self.id = id
        self.index = index
        self.label = label
        self.text = text
    }

    public var characterCount: Int {
        text.trimmingCharacters(in: .whitespacesAndNewlines).count
    }
}

/// User-controlled AI generation settings that shape both prompt behavior and
/// how the source document is chunked into real-time batches.
public nonisolated struct AIGenerationLanguageHint: Equatable, Codable, Sendable {
    public var languageCode: String
    public var displayName: String

    public init(languageCode: String, displayName: String) {
        self.languageCode = languageCode
        self.displayName = displayName
    }
}

public enum AIGenerationOutputLanguageMode: String, CaseIterable, Identifiable, Codable, Sendable {
    case auto
    case manual

    public var id: String { rawValue }

    public var title: String {
        switch self {
        case .auto: return "Auto"
        case .manual: return "Manual"
        }
    }

    public func localizedTitle(locale: Locale) -> String {
        switch self {
        case .auto: return AppLocalization.string("Auto", locale: locale)
        case .manual: return AppLocalization.string("Manual", locale: locale)
        }
    }
}

extension AIGenerationLanguageHint {
    nonisolated public func localizedDisplayName(locale: Locale) -> String {
        switch languageCode {
        case "en":
            return AppLocalization.string("English", locale: locale)
        case "ro":
            return AppLocalization.string("Romanian", locale: locale)
        case "de":
            return AppLocalization.string("German", locale: locale)
        case "es":
            return AppLocalization.string("Spanish", locale: locale)
        case "fr":
            return AppLocalization.string("French", locale: locale)
        case "it":
            return AppLocalization.string("Italian", locale: locale)
        case "pt":
            return AppLocalization.string("Portuguese", locale: locale)
        case "nl":
            return AppLocalization.string("Dutch", locale: locale)
        case "pl":
            return AppLocalization.string("Polish", locale: locale)
        case "cs":
            return AppLocalization.string("Czech", locale: locale)
        case "sk":
            return AppLocalization.string("Slovak", locale: locale)
        case "hu":
            return AppLocalization.string("Hungarian", locale: locale)
        case "tr":
            return AppLocalization.string("Turkish", locale: locale)
        case "uk":
            return AppLocalization.string("Ukrainian", locale: locale)
        case "ru":
            return AppLocalization.string("Russian", locale: locale)
        default:
            return displayName
        }
    }

    public static let supportedOutputLanguages: [AIGenerationLanguageHint] = [
        .init(languageCode: "en", displayName: "English"),
        .init(languageCode: "ro", displayName: "Romanian"),
        .init(languageCode: "de", displayName: "German"),
        .init(languageCode: "es", displayName: "Spanish"),
        .init(languageCode: "fr", displayName: "French"),
        .init(languageCode: "it", displayName: "Italian"),
        .init(languageCode: "pt", displayName: "Portuguese"),
        .init(languageCode: "nl", displayName: "Dutch"),
        .init(languageCode: "pl", displayName: "Polish"),
        .init(languageCode: "cs", displayName: "Czech"),
        .init(languageCode: "sk", displayName: "Slovak"),
        .init(languageCode: "hu", displayName: "Hungarian"),
        .init(languageCode: "tr", displayName: "Turkish"),
        .init(languageCode: "uk", displayName: "Ukrainian"),
        .init(languageCode: "ru", displayName: "Russian")
    ]
}

public nonisolated struct AIGenerationOptions: Equatable, Codable, Sendable {
    public var cardType: AICardGenerationType = .flashcards
    public var cardLevel: AICardGenerationLevel = .pro
    /// Legacy persisted field kept for backward compatibility. Delivery is
    /// adaptive now and no longer uses a user-visible fixed batch size.
    public var cardsPerBatch: Int = 3
    public var sourceDistributionMode: AISourceDistributionMode = .auto
    public var outputLanguageMode: AIGenerationOutputLanguageMode = .auto
    public var manualOutputLanguage: AIGenerationLanguageHint? = nil
    public var sourceLanguageHint: AIGenerationLanguageHint? = nil

    public init(
        cardType: AICardGenerationType = .flashcards,
        cardLevel: AICardGenerationLevel = .pro,
        cardsPerBatch: Int = 3,
        sourceDistributionMode: AISourceDistributionMode = .auto,
        outputLanguageMode: AIGenerationOutputLanguageMode = .auto,
        manualOutputLanguage: AIGenerationLanguageHint? = nil,
        sourceLanguageHint: AIGenerationLanguageHint? = nil
    ) {
        self.cardType = cardType
        self.cardLevel = cardLevel
        self.cardsPerBatch = cardsPerBatch
        self.sourceDistributionMode = sourceDistributionMode
        self.outputLanguageMode = outputLanguageMode
        self.manualOutputLanguage = manualOutputLanguage
        self.sourceLanguageHint = sourceLanguageHint
    }

    public var outputLanguageSummary: String {
        switch outputLanguageMode {
        case .auto:
            return "Auto"
        case .manual:
            return manualOutputLanguage?.displayName ?? "Auto"
        }
    }

    public func localizedOutputLanguageSummary(locale: Locale) -> String {
        switch outputLanguageMode {
        case .auto:
            return AppLocalization.string("Auto", locale: locale)
        case .manual:
            return manualOutputLanguage?.localizedDisplayName(locale: locale)
                ?? AppLocalization.string("Auto", locale: locale)
        }
    }

    enum CodingKeys: String, CodingKey {
        case cardType
        case cardLevel
        case cardsPerBatch
        case sourceDistributionMode
        case outputLanguageMode
        case manualOutputLanguage
        case sourceLanguageHint
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        cardType = try container.decodeIfPresent(AICardGenerationType.self, forKey: .cardType) ?? .flashcards
        cardLevel = try container.decodeIfPresent(AICardGenerationLevel.self, forKey: .cardLevel) ?? .pro
        cardsPerBatch = try container.decodeIfPresent(Int.self, forKey: .cardsPerBatch) ?? 3
        sourceDistributionMode = try container.decodeIfPresent(AISourceDistributionMode.self, forKey: .sourceDistributionMode) ?? .auto
        outputLanguageMode = try container.decodeIfPresent(AIGenerationOutputLanguageMode.self, forKey: .outputLanguageMode) ?? .auto
        manualOutputLanguage = try container.decodeIfPresent(AIGenerationLanguageHint.self, forKey: .manualOutputLanguage)
        sourceLanguageHint = try container.decodeIfPresent(AIGenerationLanguageHint.self, forKey: .sourceLanguageHint)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cardType, forKey: .cardType)
        try container.encode(cardLevel, forKey: .cardLevel)
        try container.encode(cardsPerBatch, forKey: .cardsPerBatch)
        try container.encode(sourceDistributionMode, forKey: .sourceDistributionMode)
        try container.encode(outputLanguageMode, forKey: .outputLanguageMode)
        try container.encodeIfPresent(manualOutputLanguage, forKey: .manualOutputLanguage)
        try container.encodeIfPresent(sourceLanguageHint, forKey: .sourceLanguageHint)
    }

    /// Resolves the per-request card quota adaptively for speed while keeping
    /// requests small enough for stable output quality.
    func resolvedCardsPerBatch(for targetCards: Int) -> Int {
        let safeTarget = max(targetCards, 1)

        let adaptiveBatchSize: Int
        switch safeTarget {
        case 1...4:
            adaptiveBatchSize = safeTarget
        case 5...12:
            adaptiveBatchSize = 4
        case 13...24:
            adaptiveBatchSize = 6
        case 25...50:
            adaptiveBatchSize = 8
        case 51...90:
            adaptiveBatchSize = 10
        case 91...180:
            adaptiveBatchSize = 10
        case 181...320:
            adaptiveBatchSize = 14
        default:
            adaptiveBatchSize = 16
        }

        return min(adaptiveBatchSize, safeTarget)
    }
}

// MARK: - AI Generated Card Model

/// The concrete response schema requested from the AI service.
public enum AIGeneratedCardContract: String, Codable, Sendable {
    case flashcard
    case quiz
}

/// AI payload for a classic flashcard response.
public struct AIFlashcardContent: Codable, Equatable, Sendable {
    public let questionZones: [String]
    public let answerZones: [String]

    public init(questionZones: [String], answerZones: [String]) {
        self.questionZones = questionZones
        self.answerZones = answerZones
    }
}

/// AI payload for a multiple-choice quiz response.
public struct AIQuizCardContent: Codable, Equatable, Sendable {
    public let questionZones: [String]
    public let choices: [String]
    public let correctIndexes: [Int]
    public let explanationZones: [String]?

    public init(
        questionZones: [String],
        choices: [String],
        correctIndexes: [Int],
        explanationZones: [String]? = nil
    ) {
        self.questionZones = questionZones
        self.choices = choices
        self.correctIndexes = correctIndexes
        self.explanationZones = explanationZones
    }

    public nonisolated var allowsMultipleCorrect: Bool {
        correctIndexes.count > 1
    }
}

/// Heterogeneous AI card payload mirroring the manual editor content families.
public enum AIGeneratedCardContent: Equatable, Sendable {
    case flashcard(AIFlashcardContent)
    case quiz(AIQuizCardContent)
}

extension AIGeneratedCardContent: Codable {
    enum CodingKeys: String, CodingKey {
        case contract
        case flashcard
        case quiz
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let contract = try container.decode(AIGeneratedCardContract.self, forKey: .contract)

        switch contract {
        case .flashcard:
            self = .flashcard(try container.decode(AIFlashcardContent.self, forKey: .flashcard))
        case .quiz:
            self = .quiz(try container.decode(AIQuizCardContent.self, forKey: .quiz))
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(contract, forKey: .contract)

        switch self {
        case .flashcard(let content):
            try container.encode(content, forKey: .flashcard)
        case .quiz(let content):
            try container.encode(content, forKey: .quiz)
        }
    }
}

extension AIGeneratedCardContent {
    /// Concrete response contract carried by this payload.
    public var contract: AIGeneratedCardContract {
        switch self {
        case .flashcard:
            return .flashcard
        case .quiz:
            return .quiz
        }
    }

    /// Short prompt preview reused by streaming progress to avoid duplicate concepts.
    var promptHint: String {
        switch self {
        case .flashcard(let content):
            return content.questionZones.joined(separator: " / ")
        case .quiz(let content):
            return content.questionZones.joined(separator: " / ")
        }
    }
}

/// A single heterogeneous card generated by the AI pipeline.
public struct AIFlashcard: Identifiable, Codable, Sendable {
    public let id: UUID
    public let content: AIGeneratedCardContent

    public init(id: UUID = UUID(), content: AIGeneratedCardContent) {
        self.id = id
        self.content = content
    }

    /// Backward-compatible convenience initializer for flashcard-style mocks/tests.
    public init(id: UUID = UUID(), question: String, answer: String) {
        self.init(
            id: id,
            content: .flashcard(
                AIFlashcardContent(
                    questionZones: Self.zoneStrings(from: question),
                    answerZones: Self.zoneStrings(from: answer)
                )
            )
        )
    }

    /// Convenience initializer for quiz outputs.
    public init(
        id: UUID = UUID(),
        questionZones: [String],
        choices: [String],
        correctIndexes: [Int],
        explanationZones: [String]? = nil
    ) {
        self.init(
            id: id,
            content: .quiz(
                AIQuizCardContent(
                    questionZones: questionZones,
                    choices: choices,
                    correctIndexes: correctIndexes,
                    explanationZones: explanationZones
                )
            )
        )
    }

    /// The concrete AI contract carried by this generated card.
    public var outputContract: AIGeneratedCardContract {
        content.contract
    }

    /// Preview string used to reduce overlapping prompts across streamed batches.
    var promptHint: String {
        content.promptHint
            .replacingOccurrences(of: AIZoneParser.zoneDelimiter, with: " / ")
            .replacingOccurrences(of: "\n", with: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private static func zoneStrings(from joinedContent: String) -> [String] {
        let parts = joinedContent
            .components(separatedBy: AIZoneParser.zoneDelimiter)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }

        return parts.isEmpty ? [joinedContent] : parts
    }
}

/// One emitted AI batch together with enough metadata to support pause/resume
/// without losing track of the source allocation it belongs to.
public struct AIFlashcardBatchChunk: Sendable {
    public let cards: [AIFlashcard]
    public let allocationID: UUID?
    public let plannedCardCount: Int
    public let shortfallCount: Int
    public let sourceLabel: String

    init(
        cards: [AIFlashcard],
        allocationID: UUID?,
        plannedCardCount: Int,
        shortfallCount: Int = 0,
        sourceLabel: String
    ) {
        self.cards = cards
        self.allocationID = allocationID
        self.plannedCardCount = plannedCardCount
        self.shortfallCount = shortfallCount
        self.sourceLabel = sourceLabel
    }
}

// MARK: - AI Generation Response

/// The top-level wrapper decoded from the AI service JSON response.
public struct AIGenerationResponse: Codable {
    public let cards: [AIFlashcard]
}
