//
//  AIGenerationState.swift
//  QuizFlash
//

import Foundation

// MARK: - AI Generation State

/// Represents the current phase of an AI flashcard generation pipeline.
///
/// Observe this value inside your ViewModel/View to drive progress UI.
public enum AIGenerationState: Equatable, Sendable {
    /// No operation in progress.
    case idle
    /// The document is being analysed for its type and quality.
    case analyzingDocument
    /// Text is being extracted from the document.
    case extractingText
    /// Flashcards are being generated by the AI model.
    ///
    /// - Parameters:
    ///   - progress: A value in `[0.0, 1.0]` indicating pipeline completion.
    ///   - foundCount: The number of flashcards produced so far.
    case generatingCards(progress: Double, foundCount: Int)
    /// Generation failed with the associated error message.
    case error(String)

    public static func == (lhs: AIGenerationState, rhs: AIGenerationState) -> Bool {
        switch (lhs, rhs) {
        case (.idle, .idle),
             (.analyzingDocument, .analyzingDocument),
             (.extractingText, .extractingText):
            return true
        case (.generatingCards(let lp, let lc), .generatingCards(let rp, let rc)):
            return lp == rp && lc == rc
        case (.error(let l), .error(let r)):
            return l == r
        default:
            return false
        }
    }
}

// MARK: - PDF Quality Info

/// Diagnostic metadata returned after analysing a PDF document's text quality.
nonisolated struct PDFAnalysisInfo: Equatable, Sendable {
    /// Normalised quality score in `[0.0, 1.0]`.
    let quality: Double
    /// Total number of pages in the document.
    let pageCount: Int
    /// Total number of characters extracted from the text layer.
    let extractedChars: Int

    /// The recommended extraction strategy based on quality.
    var recommendation: ExtractionMode {
        quality >= 0.8 ? .fast : .quality
    }

    /// A human-readable label describing the extraction quality.
    var qualityLabel: String {
        switch quality {
        case 0.8...: return "Text extracted successfully"
        case 0.5...: return "Text partially detected"
        default:     return "This PDF cannot be used – try another one"
        }
    }

    /// The SF Symbol name appropriate for the quality level.
    var qualityIcon: String {
        switch quality {
        case 0.5...: return "checkmark.circle.fill"
        default:     return "exclamationmark.triangle.fill"
        }
    }

    /// `true` when PDFKit direct extraction is reliable enough to skip OCR.
    var isGoodForFast: Bool { quality >= 0.8 }
}

/// The extraction strategy to use for a given document.
enum ExtractionMode: String, Sendable {
    /// Direct PDFKit text extraction – fast and free.
    case fast = "fast"
    /// On-device Vision OCR or GPT Vision – higher quality, higher cost.
    case quality = "quality(Premium)"
}

// MARK: - AI Generation Options

/// Card-shape profile requested by the user for AI generation.
public enum AICardGenerationType: String, CaseIterable, Identifiable, Codable, Sendable {
    case flashcards
    case match
    case quiz
    case write

    public var id: String { rawValue }

    nonisolated var title: String {
        switch self {
        case .flashcards: return "Flash Cards"
        case .match: return "Match Cards"
        case .quiz: return "Quiz Cards"
        case .write: return "Write Cards"
        }
    }

    nonisolated var subtitle: String {
        switch self {
        case .flashcards: return "Balanced active-recall question and answer cards."
        case .match: return "Short, pairable prompts and crisp matching answers."
        case .quiz: return "Multiple-choice prompts with one or more correct answers."
        case .write: return "Single-blank recall prompts with exact omitted answers."
        }
    }

    nonisolated var systemImage: String {
        switch self {
        case .flashcards: return "rectangle.stack.fill"
        case .match: return "square.grid.2x2.fill"
        case .quiz: return "questionmark.square.dashed"
        case .write: return "pencil.and.scribble"
        }
    }

    /// The concrete AI response contract selected by this generation mode.
    nonisolated var outputContract: AIGeneratedCardContract {
        switch self {
        case .flashcards:
            return .flashcard
        case .match:
            return .match
        case .quiz:
            return .quiz
        case .write:
            return .write
        }
    }
}

/// Depth and density profile requested by the user for generated cards.
public enum AICardGenerationLevel: String, CaseIterable, Identifiable, Codable, Sendable {
    case simple
    case balanced
    case advanced

    public var id: String { rawValue }

    var title: String {
        switch self {
        case .simple: return "Simple"
        case .balanced: return "Balanced"
        case .advanced: return "Advanced"
        }
    }

    var subtitle: String {
        switch self {
        case .simple: return "Focus on the clearest core facts and definitions."
        case .balanced: return "Keep the current prompt style with normal depth."
        case .advanced: return "Prefer nuanced, technical, higher-order understanding."
        }
    }
}

/// Distribution mode used to decide how much of each source segment is sent to AI.
public enum AISourceDistributionMode: String, CaseIterable, Identifiable, Codable, Sendable {
    case auto
    case manual

    public var id: String { rawValue }

    var title: String {
        switch self {
        case .auto: return "Auto"
        case .manual: return "Manual"
        }
    }

    var subtitle: String {
        switch self {
        case .auto: return "Distribute cards automatically based on detected text density."
        case .manual: return "Choose exact image or page ranges and assign card counts yourself."
        }
    }
}

/// One source range assigned to a target number of cards.
public nonisolated struct AISourceRangeAllocation: Identifiable, Equatable, Codable, Sendable {
    public var id: UUID
    public var startIndex: Int
    public var endIndex: Int
    public var cardCount: Int

    public init(
        id: UUID = UUID(),
        startIndex: Int,
        endIndex: Int,
        cardCount: Int
    ) {
        self.id = id
        self.startIndex = startIndex
        self.endIndex = endIndex
        self.cardCount = cardCount
    }
}

/// One logical text segment that can be routed independently through the AI
/// chunk planner (for example one OCR image or one PDF page).
public struct AITextSourceSegment: Identifiable, Equatable, Codable, Sendable {
    public let id: UUID
    public let index: Int
    public let label: String
    public let text: String

    public init(
        id: UUID = UUID(),
        index: Int,
        label: String,
        text: String
    ) {
        self.id = id
        self.index = index
        self.label = label
        self.text = text
    }

    public var characterCount: Int {
        text.trimmingCharacters(in: .whitespacesAndNewlines).count
    }
}

/// User-controlled AI generation settings that shape both prompt behavior and
/// how the source document is chunked into real-time batches.
public nonisolated struct AIGenerationOptions: Equatable, Codable, Sendable {
    public var cardType: AICardGenerationType = .flashcards
    public var cardLevel: AICardGenerationLevel = .balanced
    /// Legacy persisted field kept for backward compatibility. Delivery is
    /// adaptive now and no longer uses a user-visible fixed batch size.
    public var cardsPerBatch: Int = 3
    public var sourceDistributionMode: AISourceDistributionMode = .auto

    public init(
        cardType: AICardGenerationType = .flashcards,
        cardLevel: AICardGenerationLevel = .balanced,
        cardsPerBatch: Int = 3,
        sourceDistributionMode: AISourceDistributionMode = .auto
    ) {
        self.cardType = cardType
        self.cardLevel = cardLevel
        self.cardsPerBatch = cardsPerBatch
        self.sourceDistributionMode = sourceDistributionMode
    }

    /// Resolves the per-request card quota adaptively for speed while keeping
    /// requests small enough for stable output quality.
    func resolvedCardsPerBatch(for targetCards: Int) -> Int {
        let safeTarget = max(targetCards, 1)

        let adaptiveBatchSize: Int
        switch safeTarget {
        case 1...4:
            adaptiveBatchSize = safeTarget
        case 5...12:
            adaptiveBatchSize = 4
        case 13...24:
            adaptiveBatchSize = 6
        case 25...50:
            adaptiveBatchSize = 8
        case 51...90:
            adaptiveBatchSize = 10
        case 91...180:
            adaptiveBatchSize = 12
        case 181...320:
            adaptiveBatchSize = 14
        default:
            adaptiveBatchSize = 16
        }

        return min(adaptiveBatchSize, safeTarget)
    }
}

// MARK: - AI Generated Card Model

/// The concrete response schema requested from the AI service.
public enum AIGeneratedCardContract: String, Codable, Sendable {
    case flashcard
    case match
    case quiz
    case write
}

/// AI payload for a classic flashcard response.
public struct AIFlashcardContent: Codable, Equatable, Sendable {
    public let questionZones: [String]
    public let answerZones: [String]

    public init(questionZones: [String], answerZones: [String]) {
        self.questionZones = questionZones
        self.answerZones = answerZones
    }
}

/// AI payload for a multiple-choice quiz response.
public struct AIQuizCardContent: Codable, Equatable, Sendable {
    public let questionZones: [String]
    public let choices: [String]
    public let correctIndexes: [Int]
    public let explanationZones: [String]?

    public init(
        questionZones: [String],
        choices: [String],
        correctIndexes: [Int],
        explanationZones: [String]? = nil
    ) {
        self.questionZones = questionZones
        self.choices = choices
        self.correctIndexes = correctIndexes
        self.explanationZones = explanationZones
    }

    public nonisolated var allowsMultipleCorrect: Bool {
        correctIndexes.count > 1
    }
}

/// AI payload for one compact prompt-answer pair in match mode.
public struct AIMatchCardContent: Codable, Equatable, Sendable {
    public let prompt: String
    public let answer: String

    public init(prompt: String, answer: String) {
        self.prompt = prompt
        self.answer = answer
    }
}

/// AI payload for a single-blank write response.
public struct AIWriteCardContent: Codable, Equatable, Sendable {
    public let sourceText: String
    public let omittedText: String

    public init(sourceText: String, omittedText: String) {
        self.sourceText = sourceText
        self.omittedText = omittedText
    }
}

/// Heterogeneous AI card payload mirroring the manual editor content families.
public enum AIGeneratedCardContent: Equatable, Sendable {
    case flashcard(AIFlashcardContent)
    case match(AIMatchCardContent)
    case quiz(AIQuizCardContent)
    case write(AIWriteCardContent)
}

extension AIGeneratedCardContent: Codable {
    enum CodingKeys: String, CodingKey {
        case contract
        case flashcard
        case match
        case quiz
        case write
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let contract = try container.decode(AIGeneratedCardContract.self, forKey: .contract)

        switch contract {
        case .flashcard:
            self = .flashcard(try container.decode(AIFlashcardContent.self, forKey: .flashcard))
        case .match:
            self = .match(try container.decode(AIMatchCardContent.self, forKey: .match))
        case .quiz:
            self = .quiz(try container.decode(AIQuizCardContent.self, forKey: .quiz))
        case .write:
            self = .write(try container.decode(AIWriteCardContent.self, forKey: .write))
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(contract, forKey: .contract)

        switch self {
        case .flashcard(let content):
            try container.encode(content, forKey: .flashcard)
        case .match(let content):
            try container.encode(content, forKey: .match)
        case .quiz(let content):
            try container.encode(content, forKey: .quiz)
        case .write(let content):
            try container.encode(content, forKey: .write)
        }
    }
}

extension AIGeneratedCardContent {
    /// Concrete response contract carried by this payload.
    public var contract: AIGeneratedCardContract {
        switch self {
        case .flashcard:
            return .flashcard
        case .match:
            return .match
        case .quiz:
            return .quiz
        case .write:
            return .write
        }
    }

    /// Short prompt preview reused by streaming progress to avoid duplicate concepts.
    var promptHint: String {
        switch self {
        case .flashcard(let content):
            return content.questionZones.joined(separator: " / ")
        case .match(let content):
            return content.prompt
        case .quiz(let content):
            return content.questionZones.joined(separator: " / ")
        case .write(let content):
            return content.sourceText
        }
    }
}

/// A single heterogeneous card generated by the AI pipeline.
public struct AIFlashcard: Identifiable, Codable, Sendable {
    public let id: UUID
    public let content: AIGeneratedCardContent

    public init(id: UUID = UUID(), content: AIGeneratedCardContent) {
        self.id = id
        self.content = content
    }

    /// Backward-compatible convenience initializer for flashcard-style mocks/tests.
    public init(id: UUID = UUID(), question: String, answer: String) {
        self.init(
            id: id,
            content: .flashcard(
                AIFlashcardContent(
                    questionZones: Self.zoneStrings(from: question),
                    answerZones: Self.zoneStrings(from: answer)
                )
            )
        )
    }

    /// Convenience initializer for quiz outputs.
    public init(
        id: UUID = UUID(),
        questionZones: [String],
        choices: [String],
        correctIndexes: [Int],
        explanationZones: [String]? = nil
    ) {
        self.init(
            id: id,
            content: .quiz(
                AIQuizCardContent(
                    questionZones: questionZones,
                    choices: choices,
                    correctIndexes: correctIndexes,
                    explanationZones: explanationZones
                )
            )
        )
    }

    /// Convenience initializer for dedicated match outputs.
    public init(id: UUID = UUID(), matchPrompt: String, matchAnswer: String) {
        self.init(
            id: id,
            content: .match(
                AIMatchCardContent(prompt: matchPrompt, answer: matchAnswer)
            )
        )
    }

    /// Convenience initializer for write outputs.
    public init(id: UUID = UUID(), sourceText: String, omittedText: String) {
        self.init(
            id: id,
            content: .write(
                AIWriteCardContent(sourceText: sourceText, omittedText: omittedText)
            )
        )
    }

    /// The concrete AI contract carried by this generated card.
    public var outputContract: AIGeneratedCardContract {
        content.contract
    }

    /// Preview string used to reduce overlapping prompts across streamed batches.
    var promptHint: String {
        content.promptHint
            .replacingOccurrences(of: AIZoneParser.zoneDelimiter, with: " / ")
            .replacingOccurrences(of: "\n", with: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private static func zoneStrings(from joinedContent: String) -> [String] {
        let parts = joinedContent
            .components(separatedBy: AIZoneParser.zoneDelimiter)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }

        return parts.isEmpty ? [joinedContent] : parts
    }
}

/// One emitted AI batch together with enough metadata to support pause/resume
/// without losing track of the source allocation it belongs to.
public struct AIFlashcardBatchChunk: Sendable {
    public let cards: [AIFlashcard]
    public let allocationID: UUID?
    public let plannedCardCount: Int
    public let sourceLabel: String

    public init(
        cards: [AIFlashcard],
        allocationID: UUID?,
        plannedCardCount: Int,
        sourceLabel: String
    ) {
        self.cards = cards
        self.allocationID = allocationID
        self.plannedCardCount = plannedCardCount
        self.sourceLabel = sourceLabel
    }
}

// MARK: - AI Generation Response

/// The top-level wrapper decoded from the AI service JSON response.
public struct AIGenerationResponse: Codable {
    public let cards: [AIFlashcard]
}
